### PR TITLE
use the more generic Ansible module

### PR DESCRIPTION
**Pull request by altomkins**
Fedora has switched to dnf, which this module can handle

### CODE REVIEW

**Comment by hudecof** [comment]
@altomkins Fedora is not supported officially by the role. I do not have any and the CI tests are only for CentOS.
But this will work.

**Comment by hudecof** [comment]
@altomkins do you have any other patches ?
If no I will do the release for the galaxy

**Comment by altomkins** [comment]
No nothing else, and thanks for a great playbook :-)

**Comment by hudecof** [comment]
you're welcome

**Pull request merged**
